# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-09 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutCome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('game_id', models.IntegerField()),
                ('team_away', models.CharField(max_length=20)),
                ('team_home', models.CharField(max_length=20)),
                ('prediction', models.FloatField()),
            ],
        ),
    ]
