# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-09 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outcomes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outcome',
            name='prediction',
        ),
        migrations.AddField(
            model_name='outcome',
            name='pred_away',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outcome',
            name='pred_home',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
